// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/leon/gqlgen-todos/pkg/model"
)

type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewTodoResponse struct {
	Error *Error      `json:"error"`
	Todo  *model.Todo `json:"todo"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
